language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.8"
  - "3.11"
# command to install dependencies

install:
  - pip install -r SupplyHero_FastApi/requirements.txt
# command to run tests
script:
  - cd SupplyHero_FastApi
  - pytest